### ISSUE TITLE
Java errors after enabling log collection in Jenkins

### ISSUE THREAD

**Issue by ricardojdsilva87** [jenkinsci/datadog-plugin#295]
Hello we are having the following errors on Jenkins after enabling the log collection in Datadog plugin:
```
2022-07-08 16:30:58.755+0000 [id=729933]    INFO    o.d.j.p.d.c.DatadogAgentClient#reinitializeLogger: Re/Initialize Datadog-Plugin Logger: hostname = 10.241.65.43, logCollectionPort = 8126
2022-07-08 16:30:58.760+0000 [id=732176]    SEVERE    o.d.j.p.datadog.DatadogUtilities#severe: java.util.logging.ErrorManager: 2
```

Tried to do a telnet on localhost 8126 and it works.

**To Reproduce**

1. Configure the plugin using configuration as code (casc)
2. Configure the settings in a pipeline job to enable extra settings
3. Datadog agent is locally running as a container in the node with log collection enabled

**Expected behavior**
The agent should ship the logs to the central console

**Configuration:**
The casc configuration is the following:
```
unclassified:
  datadogGlobalConfiguration:
    ciInstanceName: "jenkins-prod"
    collectBuildLogs: true
    emitConfigChangeEvents: false
    emitSecurityEvents: true
    emitSystemEvents: true
    enableCiVisibility: true
    reportWith: "DSD"
    retryLogs: true
    targetLogCollectionPort: 8126
    targetPort: 8125
    targetTraceCollectionPort: 8126
```

The plugin is working correctly sending the information about the jobs into datadog (we are using the already existent Datadog dashboard to check) example:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/12953702/178034161-775768df-e8bc-4cab-90f9-6dc63d940339.png">

On the Jenkins pipeline we are setting the following:
```
pipeline {
    agent {
        kubernetes {}
    }
    options {
        // https://docs.datadoghq.com/integrations/jenkins/
        datadog(collectLogs: true, tags: ["tenant:test", "service:jenkins"])
    }
```

Also testing the connections on the UI seem to work correctly:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12953702/178034380-834a2650-3390-43a3-8613-6278e634f277.png">

We are not seeing any kind of pipeline logs information being shipped to datadog.
Is there any kind of debugging we can do? Are some of the settings incorrect?

Also a question regarding the configuration:
If we set the collectLogs variable:true in the pipeline do we need to specify the option to collect logs globally? In this case if we disable the collect logs option globally and set via the pipeline we still aren't receiving the logs, but the error logs on Jenkins mentioned above stops

**Environment and Versions:**

- Datadog Plugin version 4.0.0
- Jenkins version: 2.346.1 LTS JDK11 version
- Jenkins chart version: 4.11.11

Thanks for your help
