### ISSUE TITLE
CasC: default values are not respected

### ISSUE THREAD

**Issue by Brialius** [jenkinsci/datadog-plugin#308]
**Describe the bug**
If CasC is used to configure Datadog plugin, settings which are not explicitly set in CasC will not be changed, so settings from existing config (from global configuration page) will persist after applying CasC.

**To Reproduce**
1. Setup CasC config w/o some optional settings for Datadog plugin (w/o `enableCiVisibility` for example)
```
  datadogGlobalConfiguration:
    emitSecurityEvents: true
    emitSystemEvents: true
    hostname: "host"
    reportWith: "DSD"
    targetHost: "localhost"
    targetPort: "8125"
    targetTraceCollectionPort: "8126"
```
2. Apply CasC config
3. Go to global configuration
4. Ensure that Datadog plugin has default values in all unset settings (CI Visibility is disabled)
5. Change on of unset settings via UI on global configuration page (enable CI Visibility for example)
<img width="696" alt="image" src="https://user-images.githubusercontent.com/6441812/190409043-db3c8cb6-0dcc-4c1c-80a9-8566de1f1dbe.png">

6. Apply and save changes.
7. Apply CasC config again
8. Go to global configuration
9. See that settings are not changed (CI Visibility is still enabled)

**Expected behavior**
After applying CasC I'd expect overriding unset settings with default values. In other words I want to make sure that if CasC config is used, it is the single source of truth for Datadog plugin settings.

**Environment and Versions (please complete the following information):**
CasC plugin: [1512.vb_79d418d5fc8](https://plugins.jenkins.io/configuration-as-code)
datadog plugin: [5.0.0](https://plugins.jenkins.io/datadog)
Jenkins LTS: [2.361.1](https://www.jenkins.io/)
