### ISSUE TITLE
`branch` tag missing on metrics and events

### ISSUE THREAD

**Issue by drmaciej** [jenkinsci/datadog-plugin#334]
**Describe the bug**
`branch` is not set as a a tag on any metric, and it is not set on any events.

**Screenshots**
My plugin config is pretty much the defaults:
<img width="500" alt="Screenshot 2023-02-27 at 9 15 18 am" src="https://user-images.githubusercontent.com/21048654/221440698-c7bbc0e5-6199-4f6f-924b-8f5ad5fe5ffe.png">

nothing else is changed.

I also have an env var set in Jenkins:
```
          - name: DATADOG_JENKINS_PLUGIN_TARGET_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
```

**Environment and Versions (please complete the following information):**
Jenkins 2.375.3, on EKS 1.22
plugin: 5.3.0

**Additional context**
On metrics, e.g. `jenkins.job.completed` I get all other documented tags: `jenkins_url`, `job`, `node`, `result`, `user_id`.
On events, e.g. "Build completed", I get all other documented tags as well: `event_type`, `jenkins_url`, `job`, `node`, `result`, `user_id`.

It looks like `branch` is consistently missing across the board. Can you provide any insight into how I can troubleshoot that? I'm aware I can set tags via https://github.com/jenkinsci/datadog-plugin#pipeline-customization, but didn't want to do it for a "built-in" tag.
