### ISSUE TITLE
Incorrect value from CasC

### ISSUE THREAD

**Issue by kott-off** [jenkinsci/datadog-plugin#513]
**Describe the bug**
Datadog plugin is configured with CasC. _ciInstanceName_ value from CasC will not be applied properly to "CI Instance Name" setting in UI, it gets value from _traceServiceName_ .

**To Reproduce**
1. Setup Datadog plugin in CasC 
```
 datadogGlobalConfiguration:
    cacheBuildRuns: true
    ciInstanceName: "playground-dev.dev"
    collectBuildLogs: false
    collectBuildTraces: false
    datadogClientConfiguration:
      datadogApiConfiguration:
        apiKey:
          datadogCredentialsApiKey:
            credentialsId: "datadog_api_key"
        intake:
          datadogIntakeUrls:
            apiUrl: "https://api.datadoghq.com/api/"
            logsUrl: "https://http-intake.logs.datadoghq.com/v1/input/"
            webhooksUrl: "https://webhook-intake.datadoghq.com/api/v2/webhook/"
    emitConfigChangeEvents: false
    emitSecurityEvents: true
    emitSystemEvents: true
    enableCiVisibility: true
    hostname: "playground-dev.dev"
    refreshDogstatsdClient: false
    reportWith: "HTTP"
    showDatadogLinks: true
    targetApiURL: "https://api.datadoghq.com/api/"
    targetCredentialsApiKey: "datadog_api_key"
    targetLogIntakeURL: "https://http-intake.logs.datadoghq.com/v1/input/"
    targetWebhookIntakeURL: "https://webhook-intake.datadoghq.com/api/v2/webhook/"
    traceServiceName: "jenkins"
    useAwsInstanceHostname: false
```
2. Apply config
3. Go to global configuration
4. See that "CI Instance Name" setting is different from CasC ciInstanceName

![Image](https://github.com/user-attachments/assets/f07fb6f0-ff1c-4884-9863-7e1691654524)

**Environment and Versions:**
CasC plugin: [1953.v148f87d74b_1e](https://plugins.jenkins.io/configuration-as-code)
datadog plugin: [9.1.5](https://plugins.jenkins.io/datadog)
Jenkins LTS: [2.492.3](https://www.jenkins.io/)
